version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12 #

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved  
    
    working_directory: /tmp/ula-cli

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p ${TEST_RESULTS}
      - run: mkdir /tmp/ula-cli/output

      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run:
          name: Run unit tests
    
          # Store the results of our tests in the $TEST_RESULTS directory
          command: |
            go test ./... -tags unit

      - run:  
          name: Build release
          command: |
            make VERSION=${CIRCLE_TAG} release

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/package"
            - "/go/pkg/mod"
            - ${HOME}/.cache/go-build
            - ${HOME}/gopath/pkg/mod

      
      - persist_to_workspace:
          root: .
          paths:
            - output/*            

  publish-github-release:
    docker:
      - image: circleci/golang:1.12
      
    steps:
      - attach_workspace:
          at: .

      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$CIRCLE_TAG
            mv output/release/version.js .
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} output/release

      - run:
          name: "Push release tag to UserLAnd-Site"
          command: |
            VERSION=$CIRCLE_TAG
            git clone https://github.com/CypherpunkArmory/UserLAnd-Site.git
            mv version.js UserLAnd-Site/src/content/
            git -C UserLAnd-Site config credential.helper 'cache --timeout=120'
            git -C UserLAnd-Site config user.email "<email>"
            git -C UserLAnd-Site config user.name "Ula-cli Deployment Bot"
            git -C UserLAnd-Site checkout develop
            git -C UserLAnd-Site add -A
            git -C UserLAnd-Site commit --allow-empty -m "Upgrade ula-cli release tag to: ${VERSION}" 
            git -C UserLAnd-Site push -q https://${GITHUB_TOKEN}@github.com/CypherpunkArmory/UserLAnd-Site.git develop
            git -C UserLAnd-Site tag ula_version_${VERSION}
            git -C UserLAnd-Site push -q https://${GITHUB_TOKEN}@github.com/CypherpunkArmory/UserLAnd-Site.git ula_version_${VERSION}

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
